services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn myproject.wsgi:application --bind 0.0.0.0:8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env

  celery_worker:
    build: .
    command: celery -A myproject worker -l INFO
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    env_file:
      - .env