# Generated by Django 6.0.7 on 2026-07-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0007_remove_task_id_alter_task_title'),
    ]

    operations = [
    ]
