# Generated by Django 6.0.7 on 2026-08-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0019_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collection_name',
            field=models.CharField(blank=True, default='', help_text="ChromaDB collection identifier, e.g. 'project_1'", max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='embedding_model',
            field=models.CharField(blank=True, default='gemini-embedding-2', help_text='Model used to generate vectors (gemini-embedding-2 or gemini-embedding-001)', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='is_indexed',
            field=models.BooleanField(default=False, help_text="Indicates whether this project's code has been embedded into ChromaDB"),
        ),
        migrations.AddField(
            model_name='project',
            name='last_indexed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the repository was last embedded', null=True),
        ),
    ]
