# Generated by Django on 2026-09-03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0020_project_collection_name_project_embedding_model_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
