# Generated by Django 6.0.7 on 2026-09-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0021_delete_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
