# Generated by Django 6.0.7 on 2026-09-03 02:55

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0022_alter_task_description'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='CodeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.CharField(db_index=True, max_length=200)),
                ('filepath', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('symbol_type', models.CharField(blank=True, default='', max_length=50)),
                ('start_line', models.IntegerField(default=0)),
                ('end_line', models.IntegerField(default=0)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='coresite.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'content_hash'], name='coresite_co_project_447ed6_idx'), models.Index(fields=['project', 'chunk_id'], name='coresite_co_project_681e53_idx')],
            },
        ),
    ]
